export const AUTH_LOGIN_STARTED = 'AUTH_LOGIN_STARTED';
export const AUTH_LOGIN_INIT = 'AUTH_LOGIN_INIT';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGIN_LOGOUT = 'AUTH_LOGIN_LOGOUT';
export const UPDATE_BASIC_INFO = 'UPDATE_BASIC_INFO';